### ISSUE TITLE
有没有编译好的发行版？

### ISSUE THREAD

**Issue by jiec-msft** [wkcn/3dviewer#1]
有没有编译好的发行版？

**Comment by wkcn** [comment]
刚刚上传了Windows的版本
https://github.com/wkcn/3dviewer/releases/tag/v1.0

Linux的版本可以自己编译

**Comment by jiec-msft** [comment]
感谢！！！

**Comment by wkcn** [comment]
不客气～问题解决了，我把这个issue关闭吧。如果还有发行版方面的问题，可以重新打开这个issue : )
